In [1]:
import numpy as np

### Introdução

In [8]:
arr = np.array([1,2,3,4,5])

print("Original array:", arr)
print("Array mean:", np.mean(arr))
print("Array sum:", np.sum(arr))
print("Array squared:", np.square(arr))

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("\n2D array:")
print(matrix)
print("Matrix transpose:")
print(matrix.T)

Original array: [1 2 3 4 5]
Array mean: 3.0
Array sum: 15
Array squared: [ 1  4  9 16 25]

2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Arrays: criação, indexação e manipulação

In [9]:
import numpy as np

In [10]:
arr1 = np.array([1,2,3,4,5])
print("Array 1D:", arr1)

Array 1D: [1 2 3 4 5]


In [14]:
arr2 = np.array([[1,2,3],[4,5,6]])
print("\nArray 2D:")
print(arr2)


Array 2D:
[[1 2 3]
 [4 5 6]]


In [15]:
zeros_arr = np.zeros(5)
print("Array de zeros:", zeros_arr)

Array de zeros: [0. 0. 0. 0. 0.]


In [16]:
ones_arr = np.ones((2,3))
print("\nArray de uns:")
print(ones_arr)


Array de uns:
[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
arr = np.array([10, 20, 30, 40, 50])
print("Array original:", arr)
print("Primeiro elemento:", arr[0])
print("Último elemento:", arr[-1])
print("Elementos do índice 1 ao 3:", arr[1:4])

Array original: [10 20 30 40 50]
Primeiro elemento: 10
Último elemento: 50
Elementos do índice 1 ao 3: [20 30 40]


In [18]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nMatriz original:")
print(matriz)
print("\nElemento na linha 1, coluna 2:", matriz[1,2])
print("Segunda linha completa:", matriz[1])
print("Primeira coluna:", matriz[:,0])


Matriz original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Elemento na linha 1, coluna 2: 6
Segunda linha completa: [4 5 6]
Primeira coluna: [1 4 7]


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("\nElementos maiores que 5:", arr[arr > 5])
print("Elementos pares:", arr[arr % 2 == 0])


Elementos maiores que 5: [6 7 8 9]
Elementos pares: [2 4 6 8]


In [20]:
arr = np.array([1, 2, 3, 4, 5])
arr[0] = 10  # Modifica o primeiro elemento
print("Array modificado:", arr)

Array modificado: [10  2  3  4  5]


In [21]:
arr = np.arange(1, 10)
arr_reshape = arr.reshape(3, 3)
print("\nArray redimensionado para 3x3:")
print(arr_reshape)


Array redimensionado para 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenado = np.concatenate((arr1, arr2))
print("\nArrays concatenados:", concatenado)


Arrays concatenados: [1 2 3 4 5 6]


### Operações matemáticas

In [23]:
arr = np.array([1, 2, 3, 4, 5])
print("Array original:", arr)
print("\nArray + 2:", arr + 2)
print("Array * 3:", arr * 3)
print("Array ao quadrado:", arr ** 2)

Array original: [1 2 3 4 5]

Array + 2: [3 4 5 6 7]
Array * 3: [ 3  6  9 12 15]
Array ao quadrado: [ 1  4  9 16 25]


In [24]:
print("\nRaiz quadrada:", np.sqrt(arr))
print("Exponencial:", np.exp(arr))
print("Seno:", np.sin(arr))


Raiz quadrada: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponencial: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Seno: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


### Funções estatisticas

In [25]:
print("\nMédia:", np.mean(arr))
print("Desvio padrão:", np.std(arr))
print("Soma total:", np.sum(arr))


Média: 3.0
Desvio padrão: 1.4142135623730951
Soma total: 15


In [26]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [27]:
np.arctan?

# Exercicios

### 1. Criando Arrays
Crie um array unidimensional contendo os números de 1 a 10.

Crie uma matriz 3x3 contendo números de 1 a 9.

Crie um array de 5 elementos contendo apenas zeros.

Crie um array de dimensão (2,3) contendo apenas números um.

In [29]:
import numpy as np

In [32]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr3 = np.zeros(5)
arr3

array([0., 0., 0., 0., 0.])

In [36]:
arr4 = np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

### 2. Indexação e Fatiamento
Dado um array de 10 elementos, acesse e imprima o primeiro e o último elemento.

Extraia os elementos do índice 2 ao 6 de um array de 10 elementos.

Dada uma matriz 3x3, acesse o elemento da segunda linha e terceira coluna.

Extraia a primeira coluna de uma matriz 3x3.

In [37]:
print("Primeiro elemento:",arr1[0])
print("Último elemento:",arr1[9])

Primeiro elemento: 1
Último elemento: 10


In [38]:
print("Elementos 2 a 6:",arr1[2:6])

Elementos 2 a 6: [3 4 5 6]


In [43]:
print("Elemento 2x3",arr2[1,2])

Elemento 2x3 6


In [47]:
print("Primeira coluna:",arr2[:,0])

Primeira coluna: [1 4 7]


### 3. Indexação Booleana
Dado um array de números de 1 a 20, filtre apenas os números pares.

Encontre todos os números maiores que 10 em um array de 15 elementos.

Crie um array de 10 elementos e substitua os valores menores que 5 por zero.

In [50]:
arr5 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
print("Número pares:", arr5[arr5 % 2 == 0])

Número pares: [ 2  4  6  8 10 12 14 16 18 20]


In [53]:
arr6 = np.random.randint(1, 101, 15)
arr6

array([61, 94, 66, 32, 10, 66, 68, 67, 79,  4, 31, 79, 67, 90,  3])

In [54]:
print("Maior que 10:", arr6[arr6 > 10])

Maior que 10: [61 94 66 32 66 68 67 79 31 79 67 90]


In [60]:
arr7 = np.random.randint(1, 11, 10)
arr7

array([ 4,  6,  1,  5,  6,  4,  6,  2,  4, 10])

In [61]:
for i in range(len(arr7)):
    if arr7[i] < 5:
        arr7[i]=0
    else:
        arr7[i]
i += 1


print(arr7)

[ 0  6  0  5  6  0  6  0  0 10]


### 4. Manipulação de Arrays
Modifique o terceiro elemento de um array de 5 posições para o valor 99.

Redimensione um array de 9 elementos para uma matriz 3x3.

Concatene dois arrays de mesmo tamanho em um único array.

In [64]:
arr8 = np.arange(0,5)
arr8

array([0, 1, 2, 3, 4])

In [65]:
arr8[2] = 99
arr8

array([ 0,  1, 99,  3,  4])

In [67]:
arr9 = np.arange(1,10)
arr9

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.reshape(arr9,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
arr10 = np.arange(0,2)
arr11 = np.arange(3,5)
arr12 = np.concatenate((arr10,arr11))
arr12

array([0, 1, 3, 4])

### 5. Operações Matemáticas
Some 10 a todos os elementos de um array de 5 posições.

Multiplique todos os elementos de um array de 4 posições por 2.

Eleve todos os elementos de um array ao quadrado.

Calcule a raiz quadrada de todos os elementos de um array de 6 posições.

In [74]:
arr13 = np.arange(0,5)
arr13

array([0, 1, 2, 3, 4])

In [76]:
print(arr13 + 10)

[20 21 22 23 24]


In [77]:
arr14 = np.arange(0,4)
arr14

array([0, 1, 2, 3])

In [78]:
print(arr14 * 2)

[0 2 4 6]


In [79]:
print(arr14 ** 2 )

[0 1 4 9]


In [80]:
arr15 = np.arange(1,8)
arr15

array([1, 2, 3, 4, 5, 6, 7])

In [82]:
print(np.sqrt(arr15))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131]


### 6. Estatísticas Básicas
Calcule a média de um array de 10 elementos.

Calcule o desvio padrão de um array.

Obtenha a soma total dos elementos de uma matriz 3x3.

In [83]:
arr16 = np.arange(0,11)
arr16

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
print(np.mean(arr16))

5.0


In [85]:
print(np.std(arr16))

3.1622776601683795


In [86]:
print(np.sum(arr2))

45
