# 1. 📡 Broadcasting
Permite realizar operações entre arrays de formas diferentes sem precisar replicar dados.

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = 2
print(a + b)  # Resultado: [3 4 5]

# Com formas diferentes:
A = np.array([[1], [2], [3]])
B = np.array([10, 20, 30])
print(A + B)
# Resultado:
# [[11 21 31]
#  [12 22 32]
#  [13 23 33]]

[3 4 5]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


# 2. 🧮 Agregações
Funções para resumir dados: soma, média, desvio padrão, etc.

In [2]:
data = np.array([[1, 2, 3], [4, 5, 6]])

print(data.sum())           # Soma total
print(data.sum(axis=0))     # Soma por colunas: [5 7 9]
print(data.mean(axis=1))    # Média por linhas: [2. 5.]
print(data.std())           # Desvio padrão

21
[5 7 9]
[2. 5.]
1.707825127659933


# 3. 🔀 Manipulação Avançada de Arrays

### 🔁 Reshape & Flatten

In [3]:
arr = np.arange(6).reshape(2, 3)
print(arr)

flat = arr.flatten()  # Copia 1D
r = arr.ravel()       # Visualização 1D (não copia)

[[0 1 2]
 [3 4 5]]


### 🔄 Stack e Concatenate

In [4]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])

print(np.concatenate([a, b], axis=0))  # Linhas
print(np.vstack([a, b]))               # Igual
print(np.hstack([a.T, b.T]))           # Colunas

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### 🔁 Split e Tile

In [6]:
x = np.arange(8)
np.split(x, 4)         # Divide em partes iguais
np.tile(x, 2)          # Repete array

array([0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7])

# 4. ⚙️ Funções Universais (ufuncs)
São funções vetorizadas que aplicam operações element-wise com alta performance.

In [7]:
a = np.array([1, 2, 3])
print(np.exp(a))       # exponencial
print(np.log(a))       # log natural
print(np.sqrt(a))      # raiz quadrada
print(np.add(a, 1))    # soma

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[1.         1.41421356 1.73205081]
[2 3 4]


# 5. 🚀 Performance e Otimização

### ✅ Evite loops com operações vetorizadas

In [8]:
# Ineficiente:
res = []
for i in range(1000):
    res.append(i**2)

# Eficiente:
res = np.arange(1000) ** 2

### 🧩 Use tipos corretos e evite cópias desnecessárias

In [9]:
a = np.array([1, 2, 3], dtype=np.float32)  # Mais leve
b = a.view()     # Mesma memória

### 🔬 Benchmark com %timeit (no Jupyter)

In [10]:
%timeit np.arange(1e6) ** 2


3.56 ms ± 67.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
