# 10.1 - Álgebra linear (linalg)

## 10.1.1 - Funções para álgebra linear

**from scipy import linalg**

#### Propriedades de arrays


| Funções | Descrição |
| :-- | :-- |
| linalg.inv(arg) | Retonna a inversa de uma matriz  |
| linalg.det(arg) | Acha a determinante de uma matriz  |
| linalg.norm(arg) | Acha a norma de um vetor |
| linalg.solve(arg) | Resolve um sistema linear  |
|  linalg.eig(arg) | Retorna autovalor e autovetor |

In [2]:
from scipy import linalg
import numpy as np

In [3]:
A = np.arange(9).reshape(3,3)

In [7]:
A[0,0] = 10
linalg.det(A)

-30.000000000000046

In [8]:
linalg.inv(A)

array([[ 0.1       , -0.2       ,  0.1       ],
       [-0.2       , -2.26666667,  1.46666667],
       [ 0.1       ,  2.13333333, -1.23333333]])

In [10]:
vec = np.array([3,4,0])
linalg.norm(vec)

5.0

## 10.1.2 Exercício 1
Dadas as matrizes A,B, C e D, calcule, para cada uma, o determinante, a matriz transposta e a matriz inversa.

$$ A=
 \begin{bmatrix}
   1 & 2 \\\\
   4 & 5
  \end{bmatrix}
$$

$$ B=
 \begin{bmatrix}
   cos(\pi/4) & -sen(\pi/4) \\\\
   sen(\pi/4) & cos(\pi/4)
  \end{bmatrix}
$$

$$ C=
 \begin{bmatrix}
   2 & -2 \\\\
   -2 & 5
  \end{bmatrix}
$$

$$
D=
 \begin{bmatrix}
   2 & 2 \\\\
   4 & 4
  \end{bmatrix}
$$


Notas:
- A tem determinante diferente de zero
- B é uma matriz orgonal, sua inversa é igual a sua transposta, e seu det deve ser + ou -1
- C é uma matriz simétrica, ela é igual a sua transposta
- D possui determinante igual a zero, portanto não é inversível

In [11]:
from scipy import linalg
import numpy as np

In [24]:
A = np.array([[1,2],[4,5]])

B = np.array([[np.cos(np.pi/4),-np.sin(np.pi/4)],[np.sin(np.pi/4),np.cos(np.pi/4)]])

C = np.array([[2,-2],[-2,5]])

D = np.array([[2,2],[4,4]])

In [15]:
linalg.det(A)

-3.0

In [16]:
A.T

array([[1, 4],
       [2, 5]])

In [17]:
linalg.inv(A)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [25]:
linalg.det(B)

1.0000000000000002

In [26]:
B.T

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [27]:
linalg.inv(B)

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [21]:
linalg.det(C)

6.0

In [22]:
C.T

array([[ 2, -2],
       [-2,  5]])

In [23]:
linalg.inv(C)

array([[0.83333333, 0.33333333],
       [0.33333333, 0.33333333]])

In [28]:
linalg.det(D)

0.0

In [29]:
D.T

array([[2, 4],
       [2, 4]])

In [30]:
linalg.inv(D)

LinAlgError: singular matrix

## 10.1.3 Exercício 2
Dadas as matrizes, resolva o sistema de equação $[A].\{X\} = \{B\}$

$$ A=
 \begin{bmatrix}
   1 & 1 & 1 \\\\
   1 & 2 & 2 \\\\
   2 & 1 & 3 
\end{bmatrix}
$$

$$ X=
 \begin{bmatrix}
   x_1 \\\\
   x_2 \\\\
   x_3 
\end{bmatrix}
$$

$$ B=
 \begin{bmatrix}
   6 \\\\
   9 \\\\
   11 
\end{bmatrix}
$$




In [32]:
import numpy as np
from scipy import linalg

In [33]:
A = np.array([[1,1,1],[1,2,2],[2,1,3]])

B = np.array([6,9,11])

In [35]:
X = linalg.solve(A,B)
X

array([3., 2., 1.])

In [36]:
A@X

array([ 6.,  9., 11.])

## 10.1.4 Exercício 3
Ache os autovalores e autovetores para as matrizes abaixo.

$$ A=
 \begin{bmatrix}
   -1 & 6 \\\\
   0 & 5
  \end{bmatrix}
$$

$$ B=
 \begin{bmatrix}
   -1/3 & 0 & 0 \\\\
   0 & 1 & 0 \\\\
   0 & 0 & 1/2
  \end{bmatrix}
$$

O autovalor e autovetor se associam à matriz da seguinte forma:

$$ [A] \{X\} = \lambda \{X\} $$

In [37]:
import numpy as np
from scipy import linalg

In [38]:
A = np.array([[-1,6],[0,5]])

In [43]:
autovalor,autovetor = linalg.eig(A)
autovetor

array([[1.        , 0.70710678],
       [0.        , 0.70710678]])

In [44]:
autovetor[::,0]

array([1., 0.])

In [45]:
A@autovetor[::,0]

array([-1.,  0.])

# 10.2 - Cálculo (integrate)

## 10.2.1 - Integral

**from scipy.integrate import quad, dblquad**


| Funções | Descrição |
| :-- | :-- |
| integrate.quad(func, a, b) | Calcula a integral de uma função  |
| integrate.dbquad(func, a, b, gfun, hfun) | Calcula a integral dupla de uma função  |

https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.quad.html#scipy.integrate.quad

https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.dblquad.html#scipy.integrate.dblquad


In [47]:
import numpy as np
from scipy.integrate import quad, dblquad

In [48]:
# x**2

f_x = lambda x: x**2

In [49]:
quad(f_x, 0,10)

(333.33333333333326, 3.700743415417188e-12)

In [50]:
#check
I_x = lambda x: x**3/3
I_x(10)

333.3333333333333

In [51]:
# x**2 + y

f_xy = lambda x,y: x*y

In [52]:
dblquad(f_xy, 0,5, lambda y:0, lambda y:10)

(624.9999999999999, 6.938893903907227e-12)

In [53]:
I_xy = lambda x,y: (x**2/2)*( y**2/2)
I_xy(5,10)

625.0

## 10.2.2 Exercício 1

Dadas as funções, calcule sua integral com  x variando de 0 a 10: 
$$ A(x) = e^x $$

$$ B(x) = x^3 $$

$$ C(x) = 1/x $$



In [54]:
import numpy as np
from scipy.integrate import quad

In [56]:
A_x = lambda x: np.exp(x)
quad(A_x,0,10)

(22025.465794806725, 6.239389118119916e-10)

In [57]:
np.exp(10)-np.exp(0)

22025.465794806718

In [58]:
B_x = lambda x: x**3
quad(B_x,0,10)

(2500.0000000000005, 2.775557561562892e-11)

In [59]:
10**4/4

2500.0

In [60]:
C_x = lambda x: 1/x
quad(C_x,1,10)

(2.302585092994052, 1.748598974092929e-08)

In [61]:
np.log(10) - np.log(1)

2.302585092994046

## 10.2.3 Exercício 2
Calcule a integral dupla:
$$ A(x,y) = \iint_{A}dx.dy   $$

Considere: $ 0 \le x \le 3 $ e $ 0 \le y \le 4 $


In [63]:
import numpy as np
from scipy.integrate import dblquad

In [64]:
A_xy = lambda x,y: 1

In [65]:
dblquad(A_xy,0,3,lambda y:0,lambda y:4)

(12.0, 1.3322676295501878e-13)

## 10.2.4 - EDO

**from scipy.integrate import odeint**


| Funções | Descrição |
| :-- | :-- |
| integrate.odeint(func, y0, t) | Calcula a dada equação diferencial  |



https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.odeint.html#scipy.integrate.odeint

In [71]:
import sympy as sp

x = sp.symbols('x')

y_x = sp.Function('y_x')

dy_x = sp.Derivative(y_x(x),x)

eq = dy_x + 10*x

sp.dsolve(eq)

Eq(y_x(x), C1 - 5*x**2)

In [72]:
from scipy.integrate import odeint

In [73]:
def eq_dif(u,x):
    y,dy = u
    func = [dy, -10*x]
    return func

In [75]:
x = list(range(11))
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [76]:
odeint(eq_dif,[0,0],x)

array([[    0.        ,     0.        ],
       [   -1.66666669,    -5.00000002],
       [  -13.33333337,   -20.00000002],
       [  -45.00000006,   -45.00000002],
       [ -106.66666675,   -80.00000002],
       [ -208.33333344,  -125.00000002],
       [ -360.00000012,  -180.00000002],
       [ -571.66666681,  -245.00000002],
       [ -853.3333335 ,  -320.00000002],
       [-1215.00000019,  -405.00000002],
       [-1666.66666687,  -500.00000002]])