## 7.1 Arrays 
Acesse:
- https://numpy.org/doc/
- https://numpy.org/doc/1.18/numpy-user.pdf
- https://scipy-lectures.org/intro/numpy/array_object.html#indexing-and-slicing

#### Sobre
O Numpy é uma biblioteca que permite construirmos *arrays* multidimensionais.

#### Propriedades de arrays


| Propriedade | Retorna  | Descrição |
| :-- | :-- | :-- |
| ndim | int |  número de dimensões (axes) |
| shape |  tupla |  quantidade de dados em cada dimensão |
| size | int | número de elementos |
| dtype| dtype | tipo das variáveis dos elementos |

In [10]:
import numpy as np

a_1 = np.array([1,1,1])
a_1.ndim

1

In [9]:
a_2 = np.array([[1,2,3],[4,5,6]])
a_2.shape

(2, 3)

In [13]:
a_3 = np.arange(40).reshape(2,2,2,5)
a_3

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]],


       [[[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]]])

## 7.2 Operações com arrays

### Algumas funcionalidades do Numpy
| Comando | Tipo | Descrição |
| :-- | :-- | :-- |
| sin,cos,exp,sqrt | Função | seno,cosseno,exponencial,raíz quadrada |
| pi,nan,inf | constantes(float) | pi, similar a None, infinito |
| +,-,*,/ | operadores | operações aritimética |
| ARRAY1.dot(ARRAY2) | método | multiplicação matricial |



In [21]:
import numpy as np

a = np.sin(np.pi/2)
a

1.0

In [18]:
type(np.pi)

float

In [22]:
np.nan

nan

In [23]:
np.inf

inf

In [31]:
a_1 = np.array([1,2,3])
a_1

array([1, 2, 3])

In [33]:
a_2 = np.array([4,5,6])
a_2

array([4, 5, 6])

In [27]:
a_1 + a_2

array([[5, 7, 9]])

In [28]:
a_1 + 5

array([6, 7, 8])

In [29]:
a_1*a_2

array([[ 4, 10, 18]])

In [34]:
a_1.dot(a_2)

32

In [46]:
import sympy as sp

s_1 = sp.Matrix([[1,2,3]])
s_1

Matrix([[1, 2, 3]])

In [47]:
s_2 = sp.Matrix([4,5,6])
s_2

Matrix([
[4],
[5],
[6]])

In [48]:
s_1*s_2

Matrix([[32]])

## 7.3 Funções de criação de arrays

### Algumas funções numpy para criar arrays

| Função | Descrição |
| :-- | :-- |
| zeros(*shape*) | array preenchido com zeros |
| ones(*shape*) | array preenchido com uns |
| eye(*dimensão*) | matriz identidade |
| arange(*início, fim, passo*) | cria um array unidimensioanl |
| linspace(*início, fim, quantidade*) | cria um array unidimensioanl |
| vstack([*arrays*]) e hstack([*arrays*]) | adiciona elementos de um ou mais arrays |


Métodos para dimensionar os arrays:
 - reshape --> retorna um array com o shape indicado
 - resize --> modifica o shape do array em que está sendo aplicado



In [55]:
import numpy as np

a_4 = np.ones(6)*11
a_4

array([11., 11., 11., 11., 11., 11.])

In [59]:
a_5 = np.eye(4)
a_5.ndim

2

In [60]:
a_6 = np.arange(0,10,0.5)
a_6

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [63]:
a_7 = np.linspace(0,10,12)
a_7

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [68]:
a_8 = np.ones(8)
a_8.reshape(2,4)
a_8

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
a_9 = np.ones(8)
a_9.resize(2,4)
a_9

a_10 = np.zeros(8)
a_10.resize(2,4)
a_10

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
a_11 = np.vstack((a_9,a_10))
a_11

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
a_12 = np.hstack((a_9,a_10))
a_12

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [74]:
a_13 = np.vstack((a_11,a_9))
a_13

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 7.4 Método copy




| Método | Descrição |
| :-- | :-- |
| .copy() | faz a cópia (deep copy) do array. Cuidado! O sinal de igual não executa essa função |


Nota - a propriedade **base** retorna o array utilizado para criar o array em questão



In [75]:
import numpy as np

a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [76]:
b = a
b

array([0, 1, 2, 3, 4, 5, 6, 7])

In [77]:
a[0] = 9
a

array([9, 1, 2, 3, 4, 5, 6, 7])

In [78]:
b

array([9, 1, 2, 3, 4, 5, 6, 7])

In [79]:
a is b

True

In [80]:
c = a.copy()
c

array([9, 1, 2, 3, 4, 5, 6, 7])

In [81]:
a[0] = 1
a

array([1, 1, 2, 3, 4, 5, 6, 7])

In [82]:
c

array([9, 1, 2, 3, 4, 5, 6, 7])

In [83]:
b

array([1, 1, 2, 3, 4, 5, 6, 7])

In [84]:
c is b

False

In [85]:
d = a.reshape(2,4)
d

array([[1, 1, 2, 3],
       [4, 5, 6, 7]])

In [86]:
d is a

False

In [87]:
d.base is a

True

In [88]:
d.base

array([1, 1, 2, 3, 4, 5, 6, 7])

In [90]:
print(a.base)

None


## 7.5 Métodos matemáticos para arrays

### Alguns métodos matemáticos para arrays



| Método | Descrição |
| :-- | :-- |
| .max() / .min()  | retona os valores máximo e mínimo|
| .argmax() / .argmin() | retorna os índices de valor máximo e mínimo |
| .sum() / .mean() / .std() | soma, média e desvio padrão |
|  .cumsum() | retorna um array com a soma acumulada |



In [91]:
import numpy as np

my_array = np.arange(8).reshape(2,4)**2
my_array[0][0] =11
my_array

array([[11,  1,  4,  9],
       [16, 25, 36, 49]], dtype=int32)

In [92]:
my_array.max(axis=1)


array([11, 49], dtype=int32)

In [93]:
my_array.min(axis=1)


array([ 1, 16], dtype=int32)

In [94]:
my_array.argmax()

7

In [95]:
my_array.argmin()

1

In [96]:
my_array.sum()

151

In [97]:
my_array.mean()

18.875

In [98]:
my_array.std()

15.599979967935857

In [99]:
my_array.cumsum()

array([ 11,  12,  16,  25,  41,  66, 102, 151], dtype=int32)

## 7.6 Índices e fatias de arrays (Indexing and slicing)

### Guidelines

https://scipy-lectures.org/intro/numpy/array_object.html#indexing-and-slicing


| Sintaxe | Descrição |
| :-- | :-- |
| [i] | para 1 dimensão funciona como nas listas |
| [:i] | exibe um array que vai do índice 0 até o anterior ao i|
| [i:] | exibe um array que vai do índice posterior ao i até o último índice|
|
[::i] | exibe todos os elementos variando de i em i |
| [::-i] | exibe a sequência de elementos de trás pra frente variando de i em i |
| [a:b:c] | início, fim, step |
| [i,j] | para exibir um elemento de uma matriz |
| [i,a:b] | retorna uma fatia da linha i com elementos das colunas de a até b |
| [n,i,j] | outra dimensão, linha, coluna |


Quando criamos um subarray o numpy pode compartilhar memória entre arrays (como mostrado em aulas anteriores com a propriedade .base). Para descobrir se um array compartilha memória com outro use: **np.may_share_memory(a, c)**




In [101]:
import numpy as np

a = np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [106]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0], dtype=int32)

In [108]:
a[2:8:2]

array([ 4, 16, 36], dtype=int32)

In [110]:
b = np.arange(20).reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [111]:
b[1,1]

6

In [112]:
b[1,2:]

array([7, 8, 9])

In [113]:
b[2:,3:]

array([[13, 14],
       [18, 19]])

In [115]:
c = np.arange(40).reshape(2,4,5)
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [116]:
c[1,1,1]

26

In [117]:
d = b[2:,3:]
d

array([[13, 14],
       [18, 19]])

In [118]:
d.base

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [119]:
d.base is b

False

In [120]:
d.base is b.base

True

In [121]:
np.may_share_memory(b, d)

True

## 7.7 Operações com vetores e matrizes no Numpy


- https://numpy.org/doc/stable/reference/routines.linalg.html
- https://numpy.org/doc/stable/reference/generated/numpy.cross.html


| Método | Descrição |
| :-- | :-- |
|.dot(a,b) ou @ | retorna o produto escalar entre os vetores **a** e **b** |
| .cross(a,b) | retorna o produto vetorial entre os vetores **a** e **b** |
| .inner(a,b) e .outer(a,b) | retorna o produto interno e externo entre os vetores **a** e **b** |
| .linalg.norm(a) | retorna a norma do vetor **a** |
| .matmul(a,b) | produto entre as matrizes **a** e **b** |
| .linalg.det(A) | retorna o determinante da matriz **A** |
| .linalg.inv(A) | retorna a matriz inversa de **A** |

## Vetores

In [4]:
import numpy as np
import sympy as sp

In [2]:
a = np.array([1,2,3])
a.ndim

1

In [3]:
np.dot(a,a)

14

In [5]:
a_s = sp.Matrix([1,2,3])
a_s.T*a_s

Matrix([[14]])

In [6]:
np.inner(a,a)

14

In [7]:
np.outer(a,a)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [9]:
a_s*a_s.T

Matrix([
[1, 2, 3],
[2, 4, 6],
[3, 6, 9]])

In [10]:
a*a

array([1, 4, 9])

In [11]:
np.linalg.norm(a)

3.7416573867739413

In [12]:
np.sqrt(1**2+2**2+3**2)

3.7416573867739413

In [13]:
np.cross(a,a)

array([0, 0, 0])

In [14]:
v1 = np.array([1,0,0])
v2 = np.array([0,1,0])

np.cross(v1,v2)

array([0, 0, 1])

## Matrizes

In [15]:
#multiplicação numpy

A = np.array([[1,2],[4,4]])

np.matmul(A,A)

A@A # (cuidado com o A*A)

array([[ 9, 10],
       [20, 24]])

In [16]:
A_s = sp.Matrix([[1,2],[4,4]])

A_s*A_s


Matrix([
[ 9, 10],
[20, 24]])

In [17]:
np.linalg.det(A)

-4.0

In [18]:
np.linalg.inv(A)

array([[-1.  ,  0.5 ],
       [ 1.  , -0.25]])

In [20]:
np.linalg.inv(A)@A

array([[1., 0.],
       [0., 1.]])

## 7.8 Autovalor e autovetor


- https://numpy.org/doc/stable/reference/routines.linalg.html


| Método | Descrição |
| :-- | :-- |
| linalg.eig(A) | retorna os autovalores e autovetores da matrix **A** |

## Sympy

In [24]:
import sympy as sp

lamb = sp.symbols('lambda')
A_s = sp.Matrix([[5.,3,-1],
                 [3,4,0],
                 [-1,0,2]])

eq_carac = sp.simplify(((A_s - lamb*sp.eye(3))))
eq_carac.det()

-lambda**3 + 11.0*lambda**2 - 28.0*lambda + 18.0

In [25]:
sp.solve(eq_carac.det())

[1.00000000000000, 2.35424868893541, 7.64575131106459]

## Numpy

In [26]:
import numpy as np

A = np.array([[5,3,-1],
              [3,4,0],
              [-1,0,2]])


In [27]:
l,v = np.linalg.eig(A)
l

array([7.64575131, 1.        , 2.35424869])

## 7.9 Sistemas lineares

- https://numpy.org/doc/stable/reference/routines.linalg.html


| Método | Descrição |
| :-- | :-- |
| .linalg.solve(A, B) | resolve um sistema do tipo AX= B |

In [28]:
import numpy as np

A = np.array([[1,1,1],[1,2,2],[2,1,3]])
A

array([[1, 1, 1],
       [1, 2, 2],
       [2, 1, 3]])

In [34]:
B = np.array([[6,9,11]]).T
B

array([[ 6],
       [ 9],
       [11]])

In [35]:
np.linalg.solve(A,B)

array([[3.],
       [2.],
       [1.]])